### ISSUE TITLE
中文输入无法实现。

### ISSUE THREAD

**Issue by sherlockHlb** [millionart/Vermintide-2-Controller-Tweaker#2]
按回车会出输入框，但是转到游戏内全部是问号

**Comment by millionart** [comment]
请仔细看首页说明

**Comment by sherlockHlb** [comment]
按照操作过了，并不行
而且每次回车出现的输入框内的输入法都不一样。一直在变动
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.16299 暂缺 Build 16299

**Comment by sherlockHlb** [comment]
以及无法正常取消战斗模式，输入的时候有时候一直TTTTTTTTT

**Comment by millionart** [comment]
出现tttt的情况按一下esc再按一下1重置一下状态，这是因为在堡垒内环境比较复杂，脚本会判断失误

至于输入法的问题，steamcn上的两个玩家已经反映按照操作可以解决了
https://steamcn.com/forum.php?mod=redirect&goto=findpost&ptid=370138&pid=6162979
或者你试着只保留中文输入法，把英文去掉试试
我有空会再看一下

**Comment by millionart** [comment]
我的专业版1709之前测试按照方法是可以正常发送中文的，今天更新到了1803 17120.1，经测试也可以正常发送中文
而且我去掉相关代码后，的确是出现了发送问号的问题，这说明脚本已经可以避免此类问题

**Comment by millionart** [comment]
经检查，聊天工具独立版是有这个问题的，已经修复，请重新下载

**Comment by sherlockHlb** [comment]
Tweaker.ahk依旧异常，按回车出现的输入法一直循环出现，如A,B,EN,A,B,EN。
独立版也是一样问题。输入的内容回车后变成？？
使用无边框窗口全屏以及窗口模式全屏都是这个问题。

**Comment by millionart** [comment]
系统还是 16299 吗？更新到 17120 试试？
我这边测试完全正常啊……

**Comment by sherlockHlb** [comment]
- -~主要是每次出现的输入框都是不同的输入法就很诡异

**Comment by millionart** [comment]
方便留下steamID吗，我加一下你

**Comment by sherlockHlb** [comment]
steamID：不姓夏的夏洛克

**Comment by millionart** [comment]
问题解决了，在这里备注一下：
要保证你的中文输入法列表里**没有**英语布局的输入法
有的话删掉即可
